dist: xenial
language: python
python:
  - "3.7"
install:
  pip install flask pytest
script: pytest

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t caiohsramos/first_project .
  - docker push caiohsramos/first_project
