dist: xenial
language: python
python:
  - "3.7"
jobs:
  include:
    - stage: test    
      install: 
        pip install pytest
      script: pytest
    - stage: build
      services:
        - docker
      script:
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker build -t caiohsramos/first_project .
        - docker push caiohsramos/first_project
